create table if not exists public.land_listings (
  id bigint generated by default as identity primary key,
  name text not null,
  land_use text not null default 'Residential',
  description text not null default '',
  district text not null default 'Mbarara',
  location text not null default '',
  size text not null default '',
  price_type text not null default 'total',
  price bigint not null default 0,
  has_title boolean not null default false,
  features text[] not null default '{}'::text[],
  is_sold boolean not null default false,
  is_offer_of_day boolean not null default false,
  offer_price bigint,
  offer_end_date date,
  image_url text,
  image_lg_url text,
  gallery_urls text[] not null default '{}'::text[],
  agent_name text not null default 'Muhammad Muhumuza',
  agent_phone text not null default '256 708 124902',
  agent_company text not null default 'ZALSEEF ESTATES',
  agent_image_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.contact_inquiries (
  id bigint generated by default as identity primary key,
  land_id bigint references public.land_listings (id) on delete set null,
  land_name_snapshot text,
  land_location_snapshot text,
  land_price_snapshot bigint,
  name text not null,
  email text not null,
  phone text not null,
  message text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.seller_leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  land_location text not null,
  land_type text not null,
  size text not null,
  expected_price bigint,
  details text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_land_listings_updated_at on public.land_listings;
create trigger set_land_listings_updated_at
before update on public.land_listings
for each row
execute function public.set_updated_at();

drop trigger if exists set_contact_inquiries_updated_at on public.contact_inquiries;
create trigger set_contact_inquiries_updated_at
before update on public.contact_inquiries
for each row
execute function public.set_updated_at();

drop trigger if exists set_seller_leads_updated_at on public.seller_leads;
create trigger set_seller_leads_updated_at
before update on public.seller_leads
for each row
execute function public.set_updated_at();

alter table public.land_listings enable row level security;
alter table public.contact_inquiries enable row level security;
alter table public.seller_leads enable row level security;

drop policy if exists "Public can read listings" on public.land_listings;
create policy "Public can read listings"
on public.land_listings
for select
using (true);

drop policy if exists "Authenticated users can insert listings" on public.land_listings;
create policy "Authenticated users can insert listings"
on public.land_listings
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update listings" on public.land_listings;
create policy "Authenticated users can update listings"
on public.land_listings
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can delete listings" on public.land_listings;
create policy "Authenticated users can delete listings"
on public.land_listings
for delete
to authenticated
using (true);

drop policy if exists "Public can create inquiries" on public.contact_inquiries;
create policy "Public can create inquiries"
on public.contact_inquiries
for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated users can read inquiries" on public.contact_inquiries;
create policy "Authenticated users can read inquiries"
on public.contact_inquiries
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can manage inquiries" on public.contact_inquiries;
create policy "Authenticated users can manage inquiries"
on public.contact_inquiries
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Public can create seller leads" on public.seller_leads;
create policy "Public can create seller leads"
on public.seller_leads
for insert
to anon, authenticated
with check (true);

drop policy if exists "Authenticated users can read seller leads" on public.seller_leads;
create policy "Authenticated users can read seller leads"
on public.seller_leads
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can manage seller leads" on public.seller_leads;
create policy "Authenticated users can manage seller leads"
on public.seller_leads
for all
to authenticated
using (true)
with check (true);

insert into storage.buckets (id, name, public)
values ('land-images', 'land-images', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "Public can view land images" on storage.objects;
create policy "Public can view land images"
on storage.objects
for select
using (bucket_id = 'land-images');

drop policy if exists "Authenticated users can upload land images" on storage.objects;
create policy "Authenticated users can upload land images"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'land-images');

drop policy if exists "Authenticated users can update land images" on storage.objects;
create policy "Authenticated users can update land images"
on storage.objects
for update
to authenticated
using (bucket_id = 'land-images')
with check (bucket_id = 'land-images');

drop policy if exists "Authenticated users can delete land images" on storage.objects;
create policy "Authenticated users can delete land images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'land-images');

insert into public.land_listings (
  id,
  name,
  land_use,
  description,
  district,
  location,
  size,
  price_type,
  price,
  has_title,
  features,
  is_sold,
  is_offer_of_day,
  offer_price,
  offer_end_date,
  agent_name,
  agent_phone,
  agent_company
)
values
  (1, 'Igyereka Plot', 'Residential', 'Affordable residential plot in Igyereka. Perfect for first-time home buyers. Surveyed with clear documentation.', 'Mbarara', 'Igyereka, Mbarara', '27x55', 'total', 2300000, true, ARRAY['Surveyed', 'Affordable', 'Residential', 'Clear Title']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (2, 'Ahari Ibiiri Plot', 'Residential', 'Well-located plot in Ahari Ibiiri. Great value for money with easy access to main road.', 'Mbarara', 'Ahari Ibiiri, Mbarara', '25x50', 'total', 2900000, true, ARRAY['Road Access', 'Surveyed', 'Residential']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (3, 'Nyarubungo Plot A', 'Residential', 'Scenic plot on Nyarubungo with beautiful views. Multiple size options available.', 'Mbarara', 'Nyarubungo, Mbarara', '30x80', 'total', 3200000, true, ARRAY['Hill View', 'Good Road', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (4, 'Nyarubungo Plot B', 'Residential', 'Alternative size option in prime Nyarubungo location.', 'Mbarara', 'Nyarubungo, Mbarara', '22x85', 'total', 3200000, true, ARRAY['Hill View', 'Good Road', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (5, 'Kiyenze Plot', 'Residential', 'Affordable residential plot in developing Kiyenze area.', 'Mbarara', 'Kiyenze, Mbarara', '25x50', 'total', 3200000, true, ARRAY['Developing Area', 'Good Investment', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (6, 'Rwendezi Plot', 'Residential', 'Well-positioned plot in Rwendezi with good neighborhood.', 'Mbarara', 'Rwendezi, Mbarara', '30x55', 'total', 3300000, true, ARRAY['Quiet Area', 'Residential', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (7, 'Rwenshebashaba Plot', 'Residential', 'Affordable plot in growing Rwenshebashaba community.', 'Mbarara', 'Rwenshebashaba, Mbarara', '25x55', 'total', 3300000, true, ARRAY['Community Setting', 'Surveyed', 'Road Access']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (8, 'Karubanda Plot A', 'Residential', 'Prime residential plot in desirable Karubanda area.', 'Mbarara', 'Karubanda, Mbarara', '25x55', 'total', 3500000, true, ARRAY['Prime Location', 'Residential', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (9, 'Karubanda Plot B', 'Residential', 'Spacious residential plot in prime Karubanda location.', 'Mbarara', 'Karubanda, Mbarara', '35x50', 'total', 4500000, true, ARRAY['Spacious', 'Prime Location', 'Residential', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (10, 'Karubanda Plot C', 'Residential', 'Standard residential plot in Karubanda.', 'Mbarara', 'Karubanda, Mbarara', '25x50', 'total', 4500000, true, ARRAY['Prime Location', 'Residential', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (11, 'Igyereka Plot B', 'Residential', 'Multiple size options in popular Igyereka area.', 'Mbarara', 'Igyereka, Mbarara', '30x60', 'total', 4800000, true, ARRAY['Popular Area', 'Residential', 'Surveyed', 'Road Access']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (12, 'Igyereka Plot C', 'Residential', 'Larger plot in Igyereka for more space.', 'Mbarara', 'Igyereka, Mbarara', '30x105', 'total', 5500000, true, ARRAY['Large Plot', 'Popular Area', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (13, 'Igyereka Plot D', 'Residential', 'Executive size plot in Igyereka.', 'Mbarara', 'Igyereka, Mbarara', '35x105', 'total', 6000000, true, ARRAY['Executive Size', 'Popular Area', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (14, 'Rubeho Plot A', 'Residential', 'Well-located plot in Rubeho with good dimensions.', 'Mbarara', 'Rubeho, Mbarara', '30x50', 'total', 5000000, true, ARRAY['Good Location', 'Residential', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (15, 'Rubeho Plot B', 'Residential', 'Longer plot in Rubeho for more flexibility.', 'Mbarara', 'Rubeho, Mbarara', '25x100', 'total', 5500000, true, ARRAY['Long Plot', 'Flexible Use', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (16, 'Ahari Ibiiri Large Plot', 'Residential', 'Spacious plot in Ahari Ibiiri for larger projects.', 'Mbarara', 'Ahari Ibiiri, Mbarara', '50x100', 'total', 6000000, true, ARRAY['Large Plot', 'Good Location', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (17, 'Kabaare Kihogo Plot', 'Residential', 'Affordable plot in Kabaare Kihogo area.', 'Mbarara', 'Kabaare Kihogo, Mbarara', '30x50', 'total', 5500000, true, ARRAY['Affordable', 'Residential', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (18, 'Omukabira Plot', 'Residential', 'Well-positioned plot in Omukabira.', 'Mbarara', 'Omukabira, Mbarara', '25x50', 'total', 6500000, true, ARRAY['Good Location', 'Residential', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (19, 'Rukuba Plot', 'Residential', 'Affordable plot in Rukuba area.', 'Mbarara', 'Rukuba, Mbarara', '25x50', 'total', 6500000, true, ARRAY['Affordable', 'Residential', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (20, 'Rwenshebashaba Large Plot', 'Residential', 'Larger plot in Rwenshebashaba.', 'Mbarara', 'Rwenshebashaba, Mbarara', '25x80', 'total', 7000000, true, ARRAY['Large Plot', 'Residential', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (21, 'Rweiziringiro Plot', 'Residential', 'Well-sized plot in Rweiziringiro.', 'Mbarara', 'Rweiziringiro, Mbarara', '30x60', 'total', 7000000, true, ARRAY['Good Size', 'Residential', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (22, 'Omukabira Kangyeya Plot', 'Residential', 'Spacious plot in Omukabira Kangyeya.', 'Mbarara', 'Omukabira Kangyeya, Mbarara', '30x80', 'total', 7500000, true, ARRAY['Spacious', 'Good Location', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (23, 'Karubanda Large Plot', 'Residential', 'Large residential plot in Karubanda.', 'Mbarara', 'Karubanda, Mbarara', '25x75', 'total', 7500000, true, ARRAY['Large Plot', 'Prime Area', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (24, 'Masha Mile 1 Plot', 'Residential', 'Prime plot in Masha Mile 1.', 'Mbarara', 'Masha Mile 1, Mbarara', '50x100', 'total', 7800000, true, ARRAY['Prime Location', 'Large Plot', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (25, 'Masha Mile 2 Plot', 'Residential', 'Excellent plot in Masha Mile 2.', 'Mbarara', 'Masha Mile 2, Mbarara', '50x100', 'total', 7800000, true, ARRAY['Prime Location', 'Large Plot', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (26, 'Aharyemu Plot', 'Residential', 'Spacious plot in Aharyemu.', 'Mbarara', 'Aharyemu, Mbarara', '50x100', 'total', 7800000, true, ARRAY['Spacious', 'Good Area', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (27, 'Kaberere Town Plot', 'Residential', 'Commercial-residential plot in Kaberere Town.', 'Mbarara', 'Kaberere Town, Mbarara', '50x100', 'total', 8000000, true, ARRAY['Town Location', 'Mixed Use', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (28, 'Nyarubungo Executive Plot', 'Residential', 'Executive plot in scenic Nyarubungo.', 'Mbarara', 'Nyarubungo, Mbarara', '55x100', 'total', 8000000, true, ARRAY['Executive', 'Scenic Views', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (29, 'Omukafunda Executive Plot', 'Residential', 'Premium executive plot in Omukafunda.', 'Mbarara', 'Omukafunda, Mbarara', '50x100', 'total', 10000000, true, ARRAY['Executive', 'Premium Location', 'Surveyed', 'Utilities']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (30, 'Makenke Executive Plot', 'Residential', 'Spacious executive plot in Makenke.', 'Mbarara', 'Makenke, Mbarara', '60x100', 'total', 11000000, true, ARRAY['Executive', 'Extra Spacious', 'Premium Area', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (31, 'Karubanda Executive Plot', 'Residential', 'Prime executive plot in Karubanda.', 'Mbarara', 'Karubanda, Mbarara', '50x100', 'total', 11000000, true, ARRAY['Executive', 'Prime Location', 'Surveyed', 'Prestigious']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (32, 'Kiyenze Executive Plot', 'Residential', 'Large executive plot in Kiyenze.', 'Mbarara', 'Kiyenze, Mbarara', '60x100', 'total', 11000000, true, ARRAY['Executive', 'Large Plot', 'Good Area', 'Surveyed']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (33, 'Kaberebere Executive Plot', 'Residential', 'Premium executive plot in Kaberebere.', 'Mbarara', 'Kaberebere, Mbarara', '50x100', 'total', 11000000, true, ARRAY['Executive', 'Premium', 'Surveyed', 'Exclusive']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES'),
  (34, 'Karubanda-Rubeho Border Plot', 'Residential', 'Unique plot on the border of Karubanda and Rubeho.', 'Mbarara', 'Karubanda/Rubeho Border, Mbarara', '25x100', 'total', 12000000, true, ARRAY['Unique Location', 'Good Size', 'Surveyed', 'Prime']::text[], false, false, null, null, 'Muhammad Muhumuza', '256 708 124902', 'ZALSEEF ESTATES')
on conflict (id) do update
set
  name = excluded.name,
  land_use = excluded.land_use,
  description = excluded.description,
  district = excluded.district,
  location = excluded.location,
  size = excluded.size,
  price_type = excluded.price_type,
  price = excluded.price,
  has_title = excluded.has_title,
  features = excluded.features,
  is_sold = excluded.is_sold,
  is_offer_of_day = excluded.is_offer_of_day,
  offer_price = excluded.offer_price,
  offer_end_date = excluded.offer_end_date,
  agent_name = excluded.agent_name,
  agent_phone = excluded.agent_phone,
  agent_company = excluded.agent_company,
  updated_at = timezone('utc', now());

select setval(
  pg_get_serial_sequence('public.land_listings', 'id'),
  coalesce((select max(id) from public.land_listings), 1),
  true
);
